import {
  CONTAINER,
  DATE_SETTINGS,
  FORM_SETTINGS,
  LEAF,
  maxLength,
  NUMBER_RULES,
  optionsSetting,
  pickerSetting,
  placeholder,
  STRING_RULES,
  sizeSetting,
  TIME_SETTINGS,
  variantSetting,
} from "./descriptors";
import type { ComponentMeta, NodeType } from "./types";

/** Ordered registry of FieldNode types. Palette renders the `showInPalette` subset of
 *  this list, grouped by `category` and in this order. */
export const FIELD_REGISTRY: ComponentMeta[] = [
  {
    type: "text",
    label: "Ô nhập",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      placeholder,
      maxLength,
      { key: "allowClear", label: "Cho phép xóa", control: "checkbox" },
      { key: "showCount", label: "Hiện số ký tự", control: "checkbox" },
      { key: "prefix", label: "Tiền tố", control: "text" },
      { key: "suffix", label: "Hậu tố", control: "text" },
      { key: "prefixIcon", label: "Biểu tượng đầu", control: "icon" },
      { key: "suffixIcon", label: "Biểu tượng cuối", control: "icon" },
      { key: "addonBefore", label: "Phụ tố trước", control: "text" },
      { key: "addonAfter", label: "Phụ tố sau", control: "text" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "text",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "textarea",
    label: "Vùng văn bản",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      placeholder,
      maxLength,
      { key: "rows", label: "Số dòng", control: "number" },
      { key: "autoSize", label: "Tự co giãn", control: "checkbox" },
      { key: "allowClear", label: "Cho phép xóa", control: "checkbox" },
      { key: "showCount", label: "Hiện số ký tự", control: "checkbox" },
      sizeSetting,
    ],
    defaultValueKind: "text",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "password",
    label: "Mật khẩu",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      placeholder,
      maxLength,
      { key: "allowClear", label: "Cho phép xóa", control: "checkbox" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "none",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "number",
    label: "Số",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      { key: "min", label: "Tối thiểu", control: "number" },
      { key: "max", label: "Tối đa", control: "number" },
      { key: "step", label: "Bước nhảy", control: "number" },
      { key: "precision", label: "Số chữ số thập phân", control: "number" },
      { key: "prefix", label: "Tiền tố", control: "text" },
      { key: "prefixIcon", label: "Biểu tượng đầu", control: "icon" },
      { key: "addonBefore", label: "Phụ tố trước", control: "text" },
      { key: "addonAfter", label: "Phụ tố sau", control: "text" },
      { key: "controls", label: "Nút tăng giảm", control: "checkbox" },
      { key: "keyboard", label: "Phím mũi tên", control: "checkbox" },
      {
        key: "displayFormat",
        label: "Định dạng hiển thị",
        control: "select",
        choices: [
          { label: "Phân cách nghìn", value: "thousands" },
          { label: "Tiền tệ", value: "currency" },
          { label: "Phần trăm", value: "percent" },
        ],
      },
      { key: "currency", label: "Mã tiền tệ (vd USD)", control: "text" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "number",
    validations: NUMBER_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "select",
    label: "Danh sách chọn",
    category: "Nhập liệu",
    defaults: { options: [] },
    // Options/dataSource are authored by the bespoke DataSourceEditor (static vs remote),
    // not the generic `options` descriptor — only the behavior flags are descriptor-driven.
    settings: [
      { key: "multiple", label: "Cho phép nhiều", control: "checkbox" },
      { key: "tags", label: "Thẻ (tự nhập)", control: "checkbox" },
      { key: "showSearch", label: "Cho tìm kiếm", control: "checkbox" },
      { key: "allowClear", label: "Cho phép xóa", control: "checkbox" },
      placeholder,
      { key: "maxTagCount", label: "Số thẻ tối đa", control: "number" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "text",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "checkbox-group",
    label: "Nhóm hộp kiểm",
    category: "Nhập liệu",
    // Options/dataSource are authored by the shared DataSourceEditor (static vs remote);
    // value is an array, so no simple default-value editor.
    defaults: { options: [] },
    settings: [
      {
        key: "direction",
        label: "Hướng",
        control: "segmented",
        choices: [
          { label: "Ngang", value: "horizontal" },
          { label: "Dọc", value: "vertical" },
        ],
      },
    ],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "radio",
    label: "Nút chọn",
    category: "Nhập liệu",
    defaults: { options: [] },
    settings: [
      optionsSetting,
      {
        key: "optionType",
        label: "Hiển thị dạng",
        control: "segmented",
        choices: [
          { label: "Nút chọn", value: "default" },
          { label: "Nút bấm", value: "button" },
        ],
      },
      {
        key: "buttonStyle",
        label: "Kiểu nút",
        control: "segmented",
        choices: [
          { label: "Viền", value: "outline" },
          { label: "Đặc", value: "solid" },
        ],
      },
      sizeSetting,
    ],
    defaultValueKind: "text",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "cascader",
    label: "Chọn phân tầng",
    category: "Nhập liệu",
    // Tree options/dataSource are authored by the shared DataSourceEditor (which
    // renders the recursive TreeOptionsEditor in static mode); value is a path array.
    defaults: { options: [] },
    settings: [],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "tree-select",
    label: "Chọn dạng cây",
    category: "Nhập liệu",
    defaults: { options: [] },
    settings: [{ key: "multiple", label: "Cho phép nhiều", control: "checkbox" }],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "checkbox",
    label: "Hộp kiểm",
    category: "Nhập liệu",
    defaults: {},
    settings: [],
    defaultValueKind: "boolean",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "switch",
    label: "Công tắc",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      { key: "checkedChildren", label: "Nhãn bật", control: "text" },
      { key: "unCheckedChildren", label: "Nhãn tắt", control: "text" },
      {
        key: "size",
        label: "Kích thước",
        control: "segmented",
        choices: [
          { label: "Mặc định", value: "default" },
          { label: "Nhỏ", value: "small" },
        ],
      },
    ],
    defaultValueKind: "boolean",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "slider",
    label: "Thanh trượt",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      { key: "min", label: "Tối thiểu", control: "number" },
      { key: "max", label: "Tối đa", control: "number" },
      { key: "step", label: "Bước nhảy", control: "number" },
      { key: "range", label: "Khoảng (hai đầu)", control: "checkbox" },
      { key: "vertical", label: "Dọc", control: "checkbox" },
      { key: "dots", label: "Chấm mỗi mốc", control: "checkbox" },
    ],
    defaultValueKind: "number",
    validations: NUMBER_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "rate",
    label: "Xếp hạng",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      { key: "count", label: "Số sao", control: "number" },
      { key: "allowHalf", label: "Cho nửa sao", control: "checkbox" },
      {
        key: "character",
        label: "Biểu tượng",
        control: "segmented",
        choices: [
          { label: "Sao", value: "star" },
          { label: "Tim", value: "heart" },
          { label: "Thích", value: "like" },
        ],
      },
      { key: "allowClear", label: "Cho phép xóa", control: "checkbox" },
    ],
    defaultValueKind: "number",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "date",
    label: "Ngày",
    category: "Nhập liệu",
    defaults: {},
    settings: [pickerSetting, ...DATE_SETTINGS],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "date-range",
    label: "Khoảng ngày",
    category: "Nhập liệu",
    defaults: {},
    settings: [pickerSetting, ...DATE_SETTINGS],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "time",
    label: "Giờ",
    category: "Nhập liệu",
    defaults: {},
    settings: TIME_SETTINGS,
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "time-range",
    label: "Khoảng giờ",
    category: "Nhập liệu",
    defaults: {},
    settings: TIME_SETTINGS,
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "color",
    label: "Màu sắc",
    category: "Nhập liệu",
    defaults: {},
    settings: [],
    defaultValueKind: "text",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "upload",
    label: "Tải lên",
    category: "Nhập liệu",
    defaults: {},
    settings: [
      { key: "accept", label: "Chấp nhận (vd image/*,.pdf)", control: "text" },
      { key: "maxCount", label: "Số tệp tối đa", control: "number" },
      {
        key: "listType",
        label: "Kiểu danh sách",
        control: "segmented",
        choices: [
          { label: "Văn bản", value: "text" },
          { label: "Ảnh", value: "picture" },
          { label: "Thẻ ảnh", value: "picture-card" },
        ],
      },
      { key: "multiple", label: "Cho nhiều tệp", control: "checkbox" },
      { key: "directory", label: "Tải cả thư mục", control: "checkbox" },
      { key: "dragger", label: "Vùng kéo thả", control: "checkbox" },
    ],
    // Value is an array of file metadata — no simple default-value editor.
    defaultValueKind: "none",
    // Two palette chips for one `upload` type: a button picker and the large drop-zone
    // (seeds `dragger: true`). The dragger is R4's built-in seed of the preset idea.
    paletteVariants: [
      { id: "button", label: "Tải lên", patch: {} },
      {
        id: "dragger",
        label: "Tải lên (kéo thả)",
        hint: "Vùng kéo-thả tệp lớn",
        patch: { dragger: true },
      },
    ],
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "array",
    label: "Mảng (danh sách)",
    category: "Mảng",
    // A fresh Form List starts with no item fields; they're authored in the
    // PropertyPanel's Item fields editor. minItems/maxItems render via the
    // generic number settings below.
    defaults: { itemFields: [] },
    settings: [
      { key: "minItems", label: "Số mục tối thiểu", control: "number" },
      { key: "maxItems", label: "Số mục tối đa", control: "number" },
      {
        key: "variant",
        label: "Bố cục",
        control: "segmented",
        choices: [
          { label: "Tự động", value: "auto" },
          { label: "Thẻ", value: "card" },
          { label: "Bảng", value: "table" },
        ],
      },
      {
        key: "editInDialog",
        label: "Sửa hàng trong hộp thoại (bảng)",
        control: "checkbox",
      },
    ],
    defaultValueKind: "none",
    // One schema `type`, three palette chips: list (responsive), cards, table. Each seeds
    // `array` with a different `variant` default.
    paletteVariants: [
      {
        id: "list",
        label: "Mảng (danh sách)",
        hint: "Danh sách lặp — bảng ở màn rộng, thẻ ở màn hẹp",
        patch: { variant: "auto" },
      },
      {
        id: "card",
        label: "Mảng thẻ",
        hint: "Hàng lặp, mỗi hàng một thẻ",
        patch: { variant: "card" },
      },
      {
        id: "table",
        label: "Mảng bảng",
        hint: "Hàng lặp xếp thành bảng",
        patch: { variant: "table" },
      },
    ],
    // An array nests values per row; it IS droppable (item fields are its children).
    behavior: CONTAINER,
    showInPalette: true,
    named: true,
  },
  // --- Layout containers (value-transparent, nameless) ----------------------
  // Out of the palette until Phase E (showInPalette: false); present here so the
  // tree engine, transformer and settings panel have full metadata for them.
  {
    type: "group",
    label: "Nhóm",
    category: "Bố cục",
    defaults: { children: [] },
    settings: [],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: false,
    named: true,
  },
  {
    type: "tabs",
    label: "Tab",
    category: "Bố cục",
    // Seed two panes so a freshly dropped Tabs is usable immediately (a bare `tabs`
    // with no panes can't be filled — the palette never offers `tab-pane` directly).
    defaults: {
      children: [
        { type: "tab-pane", label: "Tab 1", children: [] },
        { type: "tab-pane", label: "Tab 2", children: [] },
      ],
    },
    settings: [],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowAppend: (_p, c) => c === "tab-pane" },
    showInPalette: true,
    named: false,
  },
  {
    type: "tab-pane",
    label: "Tab",
    category: "Bố cục",
    defaults: { label: "Tab", children: [] },
    settings: [{ key: "label", label: "Nhãn tab", control: "text" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowParents: ["tabs"] },
    showInPalette: false,
    named: false,
  },
  {
    type: "collapse",
    label: "Thu gọn",
    category: "Bố cục",
    // Seed two panels for the same reason as Tabs (palette never offers a bare panel).
    defaults: {
      children: [
        { type: "collapse-panel", label: "Mục 1", children: [] },
        { type: "collapse-panel", label: "Mục 2", children: [] },
      ],
    },
    settings: [{ key: "accordion", label: "Chỉ mở một mục", control: "checkbox" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowAppend: (_p, c) => c === "collapse-panel" },
    showInPalette: true,
    named: false,
  },
  {
    type: "collapse-panel",
    label: "Bảng",
    category: "Bố cục",
    defaults: { label: "Mục", children: [] },
    settings: [{ key: "label", label: "Nhãn bảng", control: "text" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowParents: ["collapse"] },
    showInPalette: false,
    named: false,
  },
  {
    type: "card",
    label: "Thẻ",
    category: "Bố cục",
    defaults: { children: [] },
    settings: [{ key: "title", label: "Tiêu đề", control: "text" }],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: true,
    named: false,
  },
  {
    type: "grid",
    label: "Lưới",
    category: "Bố cục",
    defaults: { cols: 2, children: [] },
    settings: [
      {
        key: "cols",
        label: "Số cột",
        control: "slider",
        min: 1,
        max: 12,
        step: 1,
      },
    ],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: true,
    named: false,
  },
  {
    type: "space",
    label: "Khoảng cách",
    category: "Bố cục",
    defaults: { children: [] },
    settings: [
      {
        key: "direction",
        label: "Hướng",
        control: "segmented",
        choices: [
          { label: "Ngang", value: "horizontal" },
          { label: "Dọc", value: "vertical" },
        ],
      },
    ],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: true,
    named: false,
  },
  {
    // A value-transparent region that re-labels its descendants (antd Form label layout).
    // Nameless like the other layout containers; `formLayout` avoids colliding with the
    // responsive `layout` (colSpan). labelCol/wrapperCol stay JSON-authorable (no scalar
    // setter for the col object, same as the root Form's FORM_SETTINGS).
    type: "form-layout",
    label: "Bố cục nhãn",
    category: "Bố cục",
    defaults: { children: [] },
    settings: [
      {
        key: "formLayout",
        label: "Kiểu nhãn",
        control: "segmented",
        choices: [
          { label: "Dọc", value: "vertical" },
          { label: "Ngang", value: "horizontal" },
          { label: "Cùng dòng", value: "inline" },
        ],
      },
      {
        key: "labelAlign",
        label: "Canh nhãn",
        control: "segmented",
        choices: [
          { label: "Phải", value: "right" },
          { label: "Trái", value: "left" },
        ],
      },
      { key: "colon", label: "Hiện dấu hai chấm", control: "checkbox" },
    ],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: true,
    named: false,
  },
  {
    // The wizard container — the first palette-visible container. Dragging it seeds two
    // `step` panes; the StepsEditor in the property panel adds/removes/reorders them.
    type: "steps",
    label: "Các bước",
    category: "Bố cục",
    defaults: {
      children: [
        { type: "step", label: "Bước 1", children: [] },
        { type: "step", label: "Bước 2", children: [] },
      ],
    },
    settings: [],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowAppend: (_p, c) => c === "step" },
    showInPalette: true,
    named: false,
  },
  {
    type: "step",
    label: "Bước",
    category: "Bố cục",
    defaults: { label: "Bước", children: [] },
    settings: [{ key: "label", label: "Nhãn bước", control: "text" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowParents: ["steps"] },
    showInPalette: false,
    named: false,
  },
  // --- Displays (static, value-less content) --------------------------------
  {
    // A nameless leaf: authored static content (heading / paragraph / note). `named:false`
    // makes newField seed it with NO name/value (parses against displayTextFieldSchema).
    type: "display-text",
    label: "Văn bản",
    category: "Hiển thị",
    defaults: { content: "Văn bản hiển thị" },
    settings: [
      { key: "content", label: "Nội dung", control: "textarea", rows: 3 },
      {
        key: "variant",
        label: "Kiểu",
        control: "segmented",
        choices: [
          { label: "Tiêu đề", value: "title" },
          { label: "Đoạn văn", value: "paragraph" },
          { label: "Văn bản", value: "text" },
        ],
      },
      { key: "level", label: "Cấp tiêu đề (1–5)", control: "number" },
      {
        key: "align",
        label: "Canh lề",
        control: "segmented",
        choices: [
          { label: "Trái", value: "left" },
          { label: "Giữa", value: "center" },
          { label: "Phải", value: "right" },
        ],
      },
    ],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: false,
  },
];

/** The root Form node's meta. It is never in the palette and never seeded by `newField`
 *  (the tree always has exactly one form root); droppable but never drag/clone/deletable. */
export const FORM_META: ComponentMeta = {
  type: "form",
  label: "Biểu mẫu",
  category: "Biểu mẫu",
  defaults: {},
  settings: FORM_SETTINGS,
  defaultValueKind: "none",
  behavior: {
    droppable: true,
    draggable: false,
    cloneable: false,
    deletable: false,
  },
  showInPalette: false,
  named: false,
};

export const BY_TYPE = new Map<NodeType, ComponentMeta>(
  [...FIELD_REGISTRY, FORM_META].map((m) => [m.type, m]),
);
