import {
  CONTAINER,
  DATE_SETTINGS,
  FORM_SETTINGS,
  LEAF,
  maxLength,
  NUMBER_RULES,
  optionsSetting,
  pickerSetting,
  placeholder,
  STRING_RULES,
  sizeSetting,
  TIME_SETTINGS,
  variantSetting,
} from "./descriptors";
import type { ComponentMeta, NodeType } from "./types";

/** Ordered registry of FieldNode types. Palette renders the `showInPalette` subset of
 *  this list, grouped by `category` and in this order. */
export const FIELD_REGISTRY: ComponentMeta[] = [
  {
    type: "text",
    label: "Text",
    category: "Input",
    defaults: {},
    settings: [
      placeholder,
      maxLength,
      { key: "allowClear", label: "Allow clear", control: "checkbox" },
      { key: "showCount", label: "Show count", control: "checkbox" },
      { key: "prefix", label: "Prefix", control: "text" },
      { key: "suffix", label: "Suffix", control: "text" },
      { key: "addonBefore", label: "Addon before", control: "text" },
      { key: "addonAfter", label: "Addon after", control: "text" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "text",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "textarea",
    label: "Textarea",
    category: "Input",
    defaults: {},
    settings: [
      placeholder,
      maxLength,
      { key: "rows", label: "Rows", control: "number" },
      { key: "autoSize", label: "Auto height", control: "checkbox" },
      { key: "allowClear", label: "Allow clear", control: "checkbox" },
      { key: "showCount", label: "Show count", control: "checkbox" },
      sizeSetting,
    ],
    defaultValueKind: "text",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "password",
    label: "Password",
    category: "Input",
    defaults: {},
    settings: [
      placeholder,
      maxLength,
      { key: "allowClear", label: "Allow clear", control: "checkbox" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "none",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "number",
    label: "Number",
    category: "Input",
    defaults: {},
    settings: [
      { key: "min", label: "Min", control: "number" },
      { key: "max", label: "Max", control: "number" },
      { key: "step", label: "Step", control: "number" },
      { key: "precision", label: "Precision (decimals)", control: "number" },
      { key: "prefix", label: "Prefix", control: "text" },
      { key: "addonBefore", label: "Addon before", control: "text" },
      { key: "addonAfter", label: "Addon after", control: "text" },
      { key: "controls", label: "Stepper handles", control: "checkbox" },
      { key: "keyboard", label: "Arrow keys", control: "checkbox" },
      {
        key: "displayFormat",
        label: "Display format",
        control: "select",
        choices: [
          { label: "Thousands", value: "thousands" },
          { label: "Currency", value: "currency" },
          { label: "Percent", value: "percent" },
        ],
      },
      { key: "currency", label: "Currency code (e.g. USD)", control: "text" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "number",
    validations: NUMBER_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "select",
    label: "Select",
    category: "Choice",
    defaults: { options: [] },
    // Options/dataSource are authored by the bespoke DataSourceEditor (static vs remote),
    // not the generic `options` descriptor — only the behavior flags are descriptor-driven.
    settings: [
      { key: "multiple", label: "Allow multiple", control: "checkbox" },
      { key: "tags", label: "Tags (free typing)", control: "checkbox" },
      { key: "showSearch", label: "Searchable", control: "checkbox" },
      { key: "allowClear", label: "Allow clear", control: "checkbox" },
      placeholder,
      { key: "maxTagCount", label: "Max tag count", control: "number" },
      sizeSetting,
      variantSetting,
    ],
    defaultValueKind: "text",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "checkbox-group",
    label: "Checkbox group",
    category: "Choice",
    // Options/dataSource are authored by the shared DataSourceEditor (static vs remote);
    // value is an array, so no simple default-value editor.
    defaults: { options: [] },
    settings: [
      {
        key: "direction",
        label: "Direction",
        control: "segmented",
        choices: [
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },
    ],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "radio",
    label: "Radio",
    category: "Choice",
    defaults: { options: [] },
    settings: [
      optionsSetting,
      {
        key: "optionType",
        label: "Render as",
        control: "segmented",
        choices: [
          { label: "Radio", value: "default" },
          { label: "Button", value: "button" },
        ],
      },
      {
        key: "buttonStyle",
        label: "Button style",
        control: "segmented",
        choices: [
          { label: "Outline", value: "outline" },
          { label: "Solid", value: "solid" },
        ],
      },
      sizeSetting,
    ],
    defaultValueKind: "text",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "cascader",
    label: "Cascader",
    category: "Choice",
    // Tree options/dataSource are authored by the shared DataSourceEditor (which
    // renders the recursive TreeOptionsEditor in static mode); value is a path array.
    defaults: { options: [] },
    settings: [],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "tree-select",
    label: "Tree select",
    category: "Choice",
    defaults: { options: [] },
    settings: [{ key: "multiple", label: "Allow multiple", control: "checkbox" }],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "checkbox",
    label: "Checkbox",
    category: "Boolean",
    defaults: {},
    settings: [],
    defaultValueKind: "boolean",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "switch",
    label: "Switch",
    category: "Boolean",
    defaults: {},
    settings: [
      { key: "checkedChildren", label: "On label", control: "text" },
      { key: "unCheckedChildren", label: "Off label", control: "text" },
      {
        key: "size",
        label: "Size",
        control: "segmented",
        choices: [
          { label: "Default", value: "default" },
          { label: "Small", value: "small" },
        ],
      },
    ],
    defaultValueKind: "boolean",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "slider",
    label: "Slider",
    category: "Number",
    defaults: {},
    settings: [
      { key: "min", label: "Min", control: "number" },
      { key: "max", label: "Max", control: "number" },
      { key: "step", label: "Step", control: "number" },
      { key: "range", label: "Range (two handles)", control: "checkbox" },
      { key: "vertical", label: "Vertical", control: "checkbox" },
      { key: "dots", label: "Dots at each step", control: "checkbox" },
    ],
    defaultValueKind: "number",
    validations: NUMBER_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "rate",
    label: "Rate",
    category: "Number",
    defaults: {},
    settings: [
      { key: "count", label: "Star count", control: "number" },
      { key: "allowHalf", label: "Allow half", control: "checkbox" },
      {
        key: "character",
        label: "Character",
        control: "segmented",
        choices: [
          { label: "Star", value: "star" },
          { label: "Heart", value: "heart" },
          { label: "Like", value: "like" },
        ],
      },
      { key: "allowClear", label: "Allow clear", control: "checkbox" },
    ],
    defaultValueKind: "number",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "date",
    label: "Date",
    category: "Date & time",
    defaults: {},
    settings: [pickerSetting, ...DATE_SETTINGS],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "date-range",
    label: "Date range",
    category: "Date & time",
    defaults: {},
    settings: [pickerSetting, ...DATE_SETTINGS],
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "time",
    label: "Time",
    category: "Date & time",
    defaults: {},
    settings: TIME_SETTINGS,
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "time-range",
    label: "Time range",
    category: "Date & time",
    defaults: {},
    settings: TIME_SETTINGS,
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "color",
    label: "Color",
    category: "Advanced",
    defaults: {},
    settings: [],
    defaultValueKind: "text",
    validations: STRING_RULES,
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "upload",
    label: "Upload",
    category: "Advanced",
    defaults: {},
    settings: [
      { key: "accept", label: "Accept (e.g. image/*,.pdf)", control: "text" },
      { key: "maxCount", label: "Max files", control: "number" },
      {
        key: "listType",
        label: "List type",
        control: "segmented",
        choices: [
          { label: "Text", value: "text" },
          { label: "Picture", value: "picture" },
          { label: "Picture card", value: "picture-card" },
        ],
      },
    ],
    // Value is an array of file metadata — no simple default-value editor.
    defaultValueKind: "none",
    behavior: LEAF,
    showInPalette: true,
    named: true,
  },
  {
    type: "array",
    label: "Array (list)",
    category: "Layout",
    // A fresh Form List starts with no item fields; they're authored in the
    // PropertyPanel's Item fields editor. minItems/maxItems render via the
    // generic number settings below.
    defaults: { itemFields: [] },
    settings: [
      { key: "minItems", label: "Min items", control: "number" },
      { key: "maxItems", label: "Max items", control: "number" },
    ],
    defaultValueKind: "none",
    // An array nests values per row; it IS droppable (item fields are its children).
    behavior: CONTAINER,
    showInPalette: true,
    named: true,
  },
  // --- Layout containers (value-transparent, nameless) ----------------------
  // Out of the palette until Phase E (showInPalette: false); present here so the
  // tree engine, transformer and settings panel have full metadata for them.
  {
    type: "group",
    label: "Group",
    category: "Layout",
    defaults: { children: [] },
    settings: [],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: false,
    named: true,
  },
  {
    type: "tabs",
    label: "Tabs",
    category: "Layout",
    defaults: { children: [] },
    settings: [],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowAppend: (_p, c) => c === "tab-pane" },
    showInPalette: false,
    named: false,
  },
  {
    type: "tab-pane",
    label: "Tab",
    category: "Layout",
    defaults: { label: "Tab", children: [] },
    settings: [{ key: "label", label: "Tab label", control: "text" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowParents: ["tabs"] },
    showInPalette: false,
    named: false,
  },
  {
    type: "collapse",
    label: "Collapse",
    category: "Layout",
    defaults: { children: [] },
    settings: [{ key: "accordion", label: "Accordion (one open)", control: "checkbox" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowAppend: (_p, c) => c === "collapse-panel" },
    showInPalette: false,
    named: false,
  },
  {
    type: "collapse-panel",
    label: "Panel",
    category: "Layout",
    defaults: { label: "Section", children: [] },
    settings: [{ key: "label", label: "Panel label", control: "text" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowParents: ["collapse"] },
    showInPalette: false,
    named: false,
  },
  {
    type: "card",
    label: "Card",
    category: "Layout",
    defaults: { children: [] },
    settings: [{ key: "title", label: "Title", control: "text" }],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: false,
    named: false,
  },
  {
    type: "grid",
    label: "Grid",
    category: "Layout",
    defaults: { cols: 2, children: [] },
    settings: [{ key: "cols", label: "Columns", control: "slider", min: 1, max: 12, step: 1 }],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: false,
    named: false,
  },
  {
    type: "space",
    label: "Space",
    category: "Layout",
    defaults: { children: [] },
    settings: [
      {
        key: "direction",
        label: "Direction",
        control: "segmented",
        choices: [
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },
    ],
    defaultValueKind: "none",
    behavior: CONTAINER,
    showInPalette: false,
    named: false,
  },
  {
    // The wizard container — the first palette-visible container. Dragging it seeds two
    // `step` panes; the StepsEditor in the property panel adds/removes/reorders them.
    type: "steps",
    label: "Steps",
    category: "Layout",
    defaults: {
      children: [
        { type: "step", label: "Step 1", children: [] },
        { type: "step", label: "Step 2", children: [] },
      ],
    },
    settings: [],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowAppend: (_p, c) => c === "step" },
    showInPalette: true,
    named: false,
  },
  {
    type: "step",
    label: "Step",
    category: "Layout",
    defaults: { label: "Step", children: [] },
    settings: [{ key: "label", label: "Step label", control: "text" }],
    defaultValueKind: "none",
    behavior: { ...CONTAINER, allowParents: ["steps"] },
    showInPalette: false,
    named: false,
  },
];

/** The root Form node's meta. It is never in the palette and never seeded by `newField`
 *  (the tree always has exactly one form root); droppable but never drag/clone/deletable. */
export const FORM_META: ComponentMeta = {
  type: "form",
  label: "Form",
  category: "Form",
  defaults: {},
  settings: FORM_SETTINGS,
  defaultValueKind: "none",
  behavior: { droppable: true, draggable: false, cloneable: false, deletable: false },
  showInPalette: false,
  named: false,
};

export const BY_TYPE = new Map<NodeType, ComponentMeta>(
  [...FIELD_REGISTRY, FORM_META].map((m) => [m.type, m]),
);
